import{a as _,S as E,i as n}from"./assets/vendor-Ca8cN8cH.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function l(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=l(e);fetch(e.href,o)}})();const d=15;async function y(r,t=1){const e="https://pixabay.com"+"/api/",o={key:"50355121-f8c083c230eef48e4f2dd2afb",q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:d},{data:i}=await _.get(e,{params:o});return i}const h=document.querySelector(".gallery"),p=document.getElementById("global-loader"),M=new E(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});function b(r){const t=r.map(({webformatURL:l,largeImageURL:s,tags:e,likes:o,views:i,comments:P,downloads:S})=>`
<li class="gallery__item">
  <a class="gallery__link" href="${s}">
    <img class="gallery__image" src="${l}" alt="${e}" loading="lazy" />
  </a>
  <ul class="info">
    <li><b>Likes</b> ${o}</li>
    <li><b>Views</b> ${i}</li>
    <li><b>Comments</b> ${P}</li>
    <li><b>Downloads</b> ${S}</li>
  </ul>
</li>`).join("");h.insertAdjacentHTML("beforeend",t),M.refresh()}function q(){h.innerHTML=""}function L(){p.classList.add("is-active")}function f(){p.classList.remove("is-active")}const v=document.querySelector(".form"),g=v.elements["search-text"],m=document.querySelector(".js-button-load");let a,c,u="";v.addEventListener("submit",O);m.addEventListener("click",R);async function R(){L(),a+=1;try{const r=await y(u,a);b(r.hits),$(),w()}catch{n.error({message:"Network error. Please try later.",position:"topRight",timeout:4e3})}finally{f()}}function w(){a<c?A():(n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:3e3}),B())}function A(){m.classList.remove("hidden")}function B(){m.classList.add("hidden")}function $(){const r=document.querySelectorAll(".gallery li");if(r.length===0)return;const t=r[0].getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}async function O(r){if(r.preventDefault(),u=g.value.trim(),a=1,c=1,u.length<1){n.info({message:"Search field is empty. Please type a keyword.",position:"topRight",timeout:3e3});return}q(),L();try{const t=await y(u,a);if(c=Math.ceil(t.totalHits/d),console.log(t.totalHits),console.log(d),console.log(c),!t.hits.length){n.warning({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:4e3}),f();return}b(t.hits),w()}catch{n.error({message:"Network error. Please try later.",position:"topRight",timeout:4e3})}f(),g.value=""}
//# sourceMappingURL=index.js.map
