import{a as E,S as M,i as s}from"./assets/vendor-Ca8cN8cH.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function c(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=c(e);fetch(e.href,o)}})();const h=15;async function m(r,t=1){const e="https://pixabay.com"+"/api/",o={key:"50355121-f8c083c230eef48e4f2dd2afb",q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:h},{data:i}=await E.get(e,{params:o});return i}const y=document.querySelector(".gallery"),g=document.querySelector(".loader"),p=document.querySelector(".loader-backdrop"),l=document.querySelector(".js-button-load"),R=new M(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});function b(r){const t=r.map(({webformatURL:c,largeImageURL:a,tags:e,likes:o,views:i,comments:_,downloads:q})=>`
<li class="gallery__item">
  <a class="gallery__link" href="${a}">
    <img class="gallery__image" src="${c}" alt="${e}" loading="lazy" />
  </a>
  <ul class="info">
    <li><b>Likes</b> ${o}</li>
    <li><b>Views</b> ${i}</li>
    <li><b>Comments</b> ${_}</li>
    <li><b>Downloads</b> ${q}</li>
  </ul>
</li>`).join("");y.insertAdjacentHTML("beforeend",t),R.refresh()}function k(){y.innerHTML=""}function L(){g.classList.remove("hidden"),p.classList.remove("hidden")}function w(){g.classList.add("hidden"),p.classList.add("hidden")}function S(r,t){r<t?A():(console.log("iziToast is",typeof s),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:3e3}),v())}function A(){l&&l.classList.remove("hidden")}function v(){l&&l.classList.add("hidden")}function B(){const r=document.querySelectorAll(".gallery li");if(r.length===0)return;const t=r[0].getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}const P=document.querySelector(".form"),f=P.elements["search-text"];let n,d,u="";P.addEventListener("submit",$);l.addEventListener("click",O);async function $(r){if(r.preventDefault(),u=f.value.trim(),n=1,d=1,u.length<1){s.info({message:"Search field is empty. Please type a keyword.",position:"topRight",timeout:3e3});return}k(),L();try{const t=await m(u,n);if(d=Math.ceil(t.totalHits/h),!t.hits.length){s.warning({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:4e3}),v();return}b(t.hits),S(n,d),console.log("End of try block reached successfully")}catch{s.error({message:"Network error. Please try later.",position:"topRight",timeout:4e3})}finally{w(),f.value=""}}async function O(){L(),n+=1;try{const r=await m(u,n);b(r.hits),B(),S(n,d)}catch{s.error({message:"Network error. Please try later.",position:"topRight",timeout:4e3})}finally{w()}}
//# sourceMappingURL=index.js.map
