import{a as M,S as E,i as l}from"./assets/vendor-Ca8cN8cH.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const m=15;async function h(r,t=1){const e="https://pixabay.com"+"/api/",o={key:"50355121-f8c083c230eef48e4f2dd2afb",q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:m},{data:i}=await M.get(e,{params:o});return i}const y=document.querySelector(".gallery"),g=document.querySelector(".loader"),p=document.querySelector(".loader-backdrop"),u=document.querySelector(".js-button-load"),R=new E(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});function L(r){const t=r.map(({webformatURL:a,largeImageURL:n,tags:e,likes:o,views:i,comments:_,downloads:q})=>`
<li class="gallery__item">
  <a class="gallery__link" href="${n}">
    <img class="gallery__image" src="${a}" alt="${e}" loading="lazy" />
  </a>
  <ul class="info">
    <li><b>Likes</b> ${o}</li>
    <li><b>Views</b> ${i}</li>
    <li><b>Comments</b> ${_}</li>
    <li><b>Downloads</b> ${q}</li>
  </ul>
</li>`).join("");y.insertAdjacentHTML("beforeend",t),R.refresh()}function $(){y.innerHTML=""}function b(){g.classList.remove("hidden"),p.classList.remove("hidden")}function w(){g.classList.add("hidden"),p.classList.add("hidden")}function S(r,t){r<t?A():(iziToast.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:3e3}),v())}function A(){u.classList.remove("hidden")}function v(){u.classList.add("hidden")}function B(){const r=document.querySelectorAll(".gallery li");if(r.length===0)return;const t=r[0].getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}const P=document.querySelector(".form"),f=P.elements["search-text"];let s,c,d="";P.addEventListener("submit",k);u.addEventListener("click",O);async function k(r){if(r.preventDefault(),d=f.value.trim(),s=1,c=1,d.length<1){l.info({message:"Search field is empty. Please type a keyword.",position:"topRight",timeout:3e3});return}$(),b();try{const t=await h(d,s);if(c=Math.ceil(t.totalHits/m),!t.hits.length){l.warning({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:4e3}),v();return}L(t.hits),S(s,c)}catch{l.error({message:"Network error. Please try later.",position:"topRight",timeout:4e3})}finally{w(),f.value=""}}async function O(){b(),s+=1;try{const r=await h(d,s);L(r.hits),B(),S(s,c)}catch{l.error({message:"Network error. Please try later.",position:"topRight",timeout:4e3})}finally{w()}}
//# sourceMappingURL=index.js.map
